# Model settings
type: 'discrete'
transition: 'marginal'                          # uniform or marginal
model: 'graph_tf'
diffusion_steps: 500
diffusion_noise_schedule: 'cosine'              # 'cosine', 'polynomial_2'
n_layers: 12

extra_features: null        # 'all', 'cycles', 'eigenvalues' or null
conditioning_fusion: concat # concat, gated, cross-attn

hidden_mlp_dims: {'X': 256, 'E': 64, 'y': 256, 'pos': 64, 'pharma_faet': 16, 'pharma_pos': 32 }

hidden_dims : {'dx': 256, 'de': 64, 'dy': 128, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 64, 'dim_ffy': 256}

lambda_train: [3, 0.4, 1, 3, 0, 1.5, 0.2, 0.5]

nu:
  p: 2.5
  x: 1
  c: 1
  e: 1.5
  y: 1


