name: 'plinder'
datadir: 'data/plinder/'
remove_h: False
random_subset: null
pin_memory: False
adaptive_loader: False
pocket_radius: 10.0
statistics_max_samples: 2000
statistics_cache_path: 'data/plinder/statistics.pt'
statistics_force_recompute: False