n_epochs: 1000

batch_size: 256
reference_batch_size: 300
lr: 0.0002
clip_grad: null          
save_model: True
num_workers: 64
ema_decay: 0.9999
progress_bar: True
weight_decay: 1e-12
scheduler: null #
seed: 0
interaction_loss_weight: 0.0
prefetch_factor: 2